/// "DO NOT PUT YOUR GOOGLE MAPS API KEY IN A PRODUCTION APP.
/// DON'T DISTRIBUTE IT.
/// WHEN YOU'RE DOING QUICK DEMOS ON-SCREEN, THAT'S OKAY;
/// BUT DON'T DO IT WITH PRODUCTION.
/// JUST SAYIN'
const String googleMapsApiKey = 'AIzaSyD8Np-by05QY2U_2EmUOFbFMQNmaAXb0mM';